apiVersion: apps/v1
kind: Deployment
metadata:
  name: company-news-deployment
  labels:
    app: company-news
spec:
  replicas: 3
  selector:
    matchLabels:
      app: company-news
  template:
    metadata:
      labels:
        app: company-news
    spec:
      containers:
      - name: company-news
        image: youhana/comapny-news-app:1.0.0
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: company-news-service
spec:
  type: LoadBalancer
  selector:
    app: company-news
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    name: http
