apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    upstream node {
      server localhost;
    }
    server {
      listen                  80;
      server_name             localhost;
      root                    localhost;
      location /images/ {
        # CHANGE ME
        proxy_pass http://di8rxk4bytog8.cloudfront.net/images/;
        expires 1y; 
      }
      location /styles/ {
        # CHANGE ME
        proxy_pass http://di8rxk4bytog8.cloudfront.net/styles/;
        expires 1y; 
      }
      location / {
        proxy_pass http://company-news-service;
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: company-news-static-deployment
  labels:
    app: company-news-static
spec:
  replicas: 2
  selector:
    matchLabels:
      app: company-news-static
  template:
    metadata:
      labels:
        app: company-news-static
    spec:
      containers:
      - name: company-news-static
        image: nginx:1.13.12-alpine
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
      # Load the configuration files for nginx
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
---
kind: Service
apiVersion: v1
metadata:
  name: company-news-static-service
spec:
  type: LoadBalancer
  selector:
    app: company-news-static
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: http
