#!/bin/bash
set -e

# deploy app deployment and service
kubectl apply -f deployment/web-app.yml

# deploy app deployment and service
kubectl apply -f deployment/web-static.yml

# smoke test to list all pods, deployments and services
kubectl get pod,deploy,svc

echo -e "Waiting for company-news app ELB to be created (60 seconds)\n"
sleep 60

echo -e "Copy the given loadbalancer URL into the browser\n"
kubectl get svc/company-news-service --template="{{range .status.loadBalancer.ingress}} {{.hostname}} {{end}}"
echo -e "\n"
kubectl get svc/company-news-static-service --template="{{range .status.loadBalancer.ingress}} {{.hostname}} {{end}}"
