# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.cpus = 2
  end

  config.vm.synced_folder "../", "/src"

  config.vm.post_up_message = "Please set AWS API credential variables && create SSH keys."

# Run the provision-vagrant.sh script
  config.vm.provision "shell", privileged: false, path: "provision"

# Set path at login to /vagrant/
  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    echo "cd /vagrant/" >> /home/vagrant/.bashrc
  SHELL

end
